export const firstIds = [
's1m1-01','s1m1-02','s1m1-05','s1m1-08','s1m2-02','s1m3-05','s1m5-01','s1m5-04',
's2m1-02','s2m1-08','s2m2-10','s2m2-11','s2m3-01','s2m3-03','s2m3-05','s2m3-10','s2m3-14','s2m3-15','s2m4-01','s2m4-09','s2m6-04','s2m6-08','s2m6-09','s2m7-01','s2m7-03','s2m7-05',
's3m1-01','s3m1-11','s3m1-19','s3m2-04','s3m2-07','s3m2-10','s3m4-01','s3m4-05','s3m4-06','s3m5-04',
's4m1-02','s4m1-03','s4m1-04','s4m1-06','s4m1-08','s4m2-03','s4m2-04','s4m2-05','s4m3-02','s4m3-05','s4m4-04','s4m5-14'];
export const sectionInfo = {
 S1:{title:'Frameworks & standards',short:'Frameworks',blueprint:'Mostly official Area II',strategy:'Recognize the framework and its job. Memorize the compact lists and distinctions; use scenarios to learn controls.',bullets:['CSF functions, tiers, and profiles; privacy vs. cyber risk','CIS control purposes and nested implementation groups','HIPAA vs. GDPR vs. PCI DSS','COBIT governance vs. management and its five domains'],research:'Frameworks/controls recur in candidate advice, but reports disagree on how much rote S1 detail matters. Prioritize purpose and application over historical dates or control numbers.'},
 S2:{title:'Systems & data',short:'Systems & data',blueprint:'Mostly official Area I',strategy:'Recall the key distinctions, then apply them to a small scenario or query. SQL needs practice, not just vocabulary.',bullets:['Cloud models, network devices, transaction/control risks','RPO/RTO, BCP/DRP, recovery sites, backup chains','Change approvals, environments, and conversions','Database keys/normal forms, SQL joins and filters, process diagrams'],research:'SQL, IT infrastructure, change management, and business resiliency recur across the selected discussions. Keep broad systems coverage: candidate reports vary.'},
 S3:{title:'Security & response',short:'Security',blueprint:'Mostly official Area II',strategy:'Learn each threat together with its mechanism and a matching control. Rehearse response actions in plain language.',bullets:['Attack distinctions and the CIA/STRIDE lists','Authentication, access models, and layered controls','Encryption, hashing, signatures, privacy, and DLP','Assessments, incident phases, response metrics, and recovery'],research:'Candidates repeatedly recommend attacks/defenses, data loss prevention, recovery, and incident response. Security shares the largest official weight range with systems/data.'},
 S4:{title:'SOC engagements',short:'SOC',blueprint:'Mostly official Area III',strategy:'Make the report distinctions automatic. Then connect scope, evidence, and exceptions to the opinion.',bullets:['SOC 1/2/3 and Type 1/2: purpose, audience, contents','Trust services categories; CUECs vs. CSOCs','Carve-out vs. inclusive; material/pervasive opinion rules','Independence, responsibilities, evidence, and representations'],research:'SOC is the most consistent emphasis in this small candidate-report sample. That is an anecdotal study signal, not a measured exam frequency; the official SOC allocation is 15–25%.'}
};
export const sources = [
 {kind:'Official exam coverage',title:'AICPA · 2026 CPA Exam Blueprints',date:'Effective January 1, 2026 · checked September 24, 2026',url:'https://assets.ctfassets.net/rb9cdnjh59cm/71s84dkfo3KEsoLlz4vv6G/f4314469ec5368b5b4dd0d0184f00a71/CPA_Exam_Blueprints_2026.pdf',note:'ISC pages ISC2–ISC16 describe the official domains, weights, skills, and representative tasks. The S1–S4 folders are course units, not these three official areas.'},
 {kind:'Official exam changes',title:'AICPA · 2026 blueprint changes',date:'Effective January 1, 2026',url:'https://assets.ctfassets.net/rb9cdnjh59cm/5CsrSRU2mFGsmWEo9FqwLy/12e2b5ac1af2fe494bbfa8666776a1d1/Summary_of_Changes_to_the_Exam_Blueprints_effective_01012026.pdf',note:'The ISC changes are not intended to significantly change the nature or scope of eligible content. The document updates references including HIPAA and NIST Privacy Framework.'},
 {kind:'Candidate anecdotes',title:'r/CPA · ISC on Saturday (2nd attempt)',date:'July 20–21, 2026',url:'https://www.reddit.com/r/CPA/comments/1v1xzuf/isc_on_saturday_2nd_attempt/',note:'Broad study advice emphasizes SQL, attack types, CIS controls, continuity/backups, DLP, incident response, and SOC distinctions. Self-selected advice, not exam statistics.'},
 {kind:'Candidate anecdotes',title:'r/CPA · Just got out of ISC',date:'July 27, 2026',url:'https://www.reddit.com/r/CPA/comments/1v8eto6/just_got_out_of_isc_not_good_not_great/',note:'General preparation discussion highlights change management, resilience, cyber defenses, and SOC. We use topic-level advice only, not recalled exam items or claimed percentages.'},
 {kind:'Candidate anecdotes',title:'r/CPA · Just took ISC',date:'April 21–23, 2026',url:'https://www.reddit.com/r/CPA/comments/1srxtm3/just_took_isc_idk_what_to_think/',note:'Participants highlight both SOC and IT infrastructure and describe varying experiences. This counters the idea that only SOC deserves preparation.'},
 {kind:'Primary framework source',title:'NIST · Cybersecurity Framework 2.0',date:'February 26, 2024',url:'https://www.nist.gov/news-events/news/2024/02/nist-releases-version-20-landmark-cybersecurity-framework',note:'Confirms the six-function model including Govern.'},
 {kind:'Primary framework source',title:'NIST · Privacy Framework FAQ',date:'Checked September 24, 2026',url:'https://www.nist.gov/privacy-framework/frequently-asked-questions',note:'Clarifies that the Privacy Framework has five functions; cybersecurity functions can be used alongside them.'},
 {kind:'Primary framework source',title:'CIS · The 18 Critical Security Controls',date:'v8.1 · checked September 24, 2026',url:'https://www.cisecurity.org/controls/cis-controls-list',note:'Reference for the control purposes. The study deck follows the v8/v8.1 control organization in the notes.'},
 {kind:'Primary framework source',title:'ISACA · COBIT 2019 and COBIT 5 comparison',date:'2020',url:'https://www.isaca.org/resources/news-and-trends/industry-news/2020/cobit-2019-and-cobit-5-comparison',note:'Reference for governance-system and governance-framework principles.'},
 {kind:'Clarification',title:'HHS · Covered entities and business associates',date:'Reviewed August 21, 2024',url:'https://www.hhs.gov/hipaa/for-professionals/covered-entities/index.html',note:'Business associates and covered entities are separate categories with HIPAA obligations.'},
 {kind:'Clarification',title:'HHS · Breach Notification Rule',date:'Checked September 24, 2026',url:'https://www.hhs.gov/hipaa/for-professionals/breach-notification/index.html',note:'Notification of affected individuals is without unreasonable delay, no later than 60 days after discovery, subject to the rule’s conditions.'},
 {kind:'Historical slide correction',title:'European Commission · EU–US Data Privacy Framework adoption',date:'July 10, 2023',url:'https://ec.europa.eu/commission/presscorner/api/files/document/print/en/ip_23_3721/IP_23_3721_EN.pdf',note:'The slide saying no successor had been agreed after Privacy Shield is out of date; this decision established a replacement mechanism for participating organizations.'},
 {kind:'Current guidance clarification',title:'NIST · SP 800-63B-4 authentication guidance',date:'2025 revision · checked September 24, 2026',url:'https://pages.nist.gov/800-63-4/sp800-63b.html',note:'The blanket periodic-password-rotation advice in the slides is not current NIST guidance. Follow the version and assumptions specified in a question.'},
 {kind:'Version clarification',title:'NIST · SP 800-61 Rev. 3',date:'Final April 3, 2025',url:'https://csrc.nist.gov/pubs/sp/800/61/r3/final',note:'The slides use the older four-stage Rev. 2 incident model. Rev. 3 integrates incident response into CSF 2.0. The historical model is explicitly labeled in the deck.'}
];
export const clarifications=[
 ['S1 · NIST privacy functions','The combined eight-function slide is not the standalone Privacy Framework function list. The deck teaches its five functions and labels the CSF overlap.'],
 ['S1 · HIPAA roles and notification','Business associates are distinct from covered entities. “Within 60 days” is an outer limit, not permission to delay a necessary notice.'],
 ['S1 · Privacy Shield history','The slide’s “until a new agreement” statement is historical; the EU–US Data Privacy Framework decision was adopted in July 2023.'],
 ['S2 · Obvious unrelated slide text','The Agile slide contains secured-debt/collateral sentences unrelated to this topic. These appear to be a slide-editing error and are excluded from the study material.'],
 ['S3 · Crypto and password storage','Encryption alone does not prove origin; a plain hash alone does not authenticate the sender. A password verifier’s hashes are different from a password manager’s recoverable encrypted vault.'],
 ['S3 · Current versus historical guidance','Periodic password rotation and the four-stage NIST incident model are version-sensitive. The deck flags their context instead of presenting the slides as timeless current rules.'],
 ['S3 · Disposal and exercises','File deletion is not verified sanitization; degaussing does not apply to SSDs. Tabletop discussion is distinct from technical exercise or penetration testing.'],
 ['Scope · Condensed concept coverage','Repeated examples, historical trivia, and full sample-report wording are consolidated into original recall/application prompts. Use the private notes for full report wording, diagrams, and deeper examples.']
];
